apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: sopes2
  labels:
    app: backend-deployment
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: backend-deployment
