apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: sopes2
spec:
  selector:
    app: frontend-deployment
  ports:
    - port: 3001
      targetPort: 3001
  type: LoadBalancer