apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: sopes2
  labels:
    app: frontend-deployment
spec:
  replicas: 2
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: frontend-deployment
        image: docker.io/oscarllamas6/frontend-sopes2:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 3001